/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"APP.h"

uint16_t RFID_CARD_Enter;
uint16_t RFID_CARD_EXIT;

uint8_t pass[3] ={0};

unsigned char Available_Slots='3';
uint8_t Search_Done = 0;

volatile uint8_t enterFlag=0;
volatile uint8_t ExitFlag=0;

volatile uint8_t PIR1=0;
volatile uint8_t PIR2=0;


#define MAX_IDS 3
#define ID_LENGTH 3

uint8_t Admin_IDs[MAX_IDS][ID_LENGTH] = {0};  // array to store IDs

void RFID_CARD_Enter_CallBack(void);
void RFID_CARD_EXIT_CallBack(void);

void LCD_Welcome(void);
void LCD_Display_Empty_Slots(void);
void LEDs_Init(void);
void PIRs_Iint(void);
void Store_IDs_From_Admin(void);

void Entring_Fun(void);
void Exit_Fun(void);


UART_ConfigPin_t UARTpins1;
UART_ConfigPin_t UARTpins2;

Led_Config_t red_led;
Led_Config_t green_led;

Lcd_ConfigType LCD1 =
{
    .Mode = LCD_4BIT_MODE,
    .RW_Used = LCD_RW_NOT_USED,

    /* Control pins */
    .RS = { PORTA, GPIO_PIN5 },   // Register Select
    .EN = { PORTA, GPIO_PIN6 },   // Enable pin

    /* RW not used */
    .RW = { NULL, 0 },

    .DataPins =
    {
        /* D0-D3 not used in 4-bit mode */
        { NULL, 0 },
        { NULL, 0 },
        { NULL, 0 },
        { NULL, 0 },

        /* D4-D7 connected to PA12-PA15 */
        { PORTA, GPIO_PIN12 }, // D4
        { PORTA, GPIO_PIN13 }, // D5
        { PORTA, GPIO_PIN14 }, // D6
        { PORTA, GPIO_PIN15 }  // D7
    }
};

Lcd_ConfigType LCD2 =
{
    .Mode = LCD_4BIT_MODE,
    .RW_Used = LCD_RW_NOT_USED,

    /* Control pins */
    .RS = { PORTB, GPIO_PIN11 },   // Register Select
    .EN = { PORTB, GPIO_PIN10 },   // Enable pin

    /* RW not used */
    .RW = { NULL, 0 },

    .DataPins =
    {
        /* D0-D3 not used in 4-bit mode */
        { NULL, 0 },
        { NULL, 0 },
        { NULL, 0 },
        { NULL, 0 },

        /* D4-D7 connected to PA12-PA15 */
        { PORTB, GPIO_PIN12 }, // D4
        { PORTB, GPIO_PIN13 }, // D5
        { PORTB, GPIO_PIN14 }, // D6
        { PORTB, GPIO_PIN15 }  // D7
    }
};

/* Key mapping for 3x4 keypad */
const uint8_t KeyPad_Keys[4][3] =
{
    {'#','0','*'},   // Row 0
    {'9','8','7'},   // Row 1
    {'6','5','4'},   // Row 2
    {'3','2','1'}    // Row 3
};

/* Keypad object */
KeyPad_ConfigType Keypad3x4 =
{
    .Rows = 4,
    .Cols = 3,

    .RowPins =
    {
        { PORTB, GPIO_PIN0 },
        { PORTB, GPIO_PIN1 },
        { PORTB, GPIO_PIN3 },
        { PORTB, GPIO_PIN4 }
    },

    .ColPins =
    {
        { PORTB, GPIO_PIN5 },
        { PORTB, GPIO_PIN6 },
        { PORTB, GPIO_PIN7 }
    },

    .KeyMap = KeyPad_Keys
};
int main(void)
{

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
	KeyPad_Init(&Keypad3x4);

	Timer2_init();
	Servo1_Entry_Gate_Init();
	Servo2_Exit_Gate_Init();
	//==========================UART1 INIT=============================

	UARTpins1.BaudRate=UART_BaudRate_115200;
	UARTpins1.Payload_Length=UART_Payload_Length_8B;
	UARTpins1.HW_FlowCTL=UART_HW_FlowCTL_NONE;
	UARTpins1.IRQ_Enable= UART_IRQ_Enable_RXNE;
	UARTpins1.Mode=UART_Mode_TX_RX;
	UARTpins1.Parity=UART_Parity_NONE;
	UARTpins1.StopBits=UART_StopBits_1;
	UARTpins1.UART=UART1;
	UARTpins1.p_IRQ_CallBack=RFID_CARD_Enter_CallBack;
	UART_Init(&UARTpins1);

	//==========================UART2 INIT=============================

	UARTpins2.BaudRate=UART_BaudRate_115200;
	UARTpins2.Payload_Length=UART_Payload_Length_8B;
	UARTpins2.HW_FlowCTL=UART_HW_FlowCTL_NONE;
	UARTpins2.IRQ_Enable=UART_IRQ_Enable_RXNE;
	UARTpins2.Mode=UART_Mode_TX_RX;
	UARTpins2.Parity=UART_Parity_NONE;
	UARTpins2.StopBits=UART_StopBits_1;
	UARTpins2.UART=UART2;
	UARTpins2.p_IRQ_CallBack=RFID_CARD_EXIT_CallBack;
	UART_Init(&UARTpins2);

	Lcd_Init(&LCD1);
	Lcd_Init(&LCD2);

	LEDs_Init();
	PIRs_Iint();


	/*==========Enter IDs To Store In Array Pass==========*/
	 Store_IDs_From_Admin();

	/*Dash Bord LCD*/
	LCD_Welcome();
	dms(200);
	LCD_Display_Empty_Slots();

	while(1)
	{
		for(uint8_t i = 0; i < ID_LENGTH; i++)
		{
		    UART_Receive_Data(&UARTpins1, &RFID_CARD_Enter);   // Receive 1 byte
		    pass[i] = (uint8_t)RFID_CARD_Enter;               // Store in pass array
		}

		UART_Receive_Data(&UARTpins2,&RFID_CARD_EXIT);
		if(enterFlag)
		{
			enterFlag=0;
			Entring_Fun();
		}
		if(ExitFlag)
		{
			ExitFlag=0;
			Exit_Fun();
		}

	}

	return 0;
}


/*Call Back For UART*/
void RFID_CARD_Enter_CallBack(void)
{
	UART_Send_Data(&UARTpins1,&RFID_CARD_Enter);
	enterFlag=1;
}

void RFID_CARD_EXIT_CallBack(void)
{
	UART_Send_Data(&UARTpins2,&RFID_CARD_EXIT);
	ExitFlag=1;
}



void LCD_Welcome(void)
{
    /* Clear display */
    Lcd_SendCommand(&LCD1, 0x01);

    /* Set cursor to row 0, column 0 */
    Lcd_SetCursor(&LCD1, 0, 0);
    Lcd_SendString(&LCD1, (uint8_t*)"Welcome in");

    /* Set cursor to row 1, column 0 */
    Lcd_SetCursor(&LCD1, 1, 0);
    Lcd_SendString(&LCD1, (uint8_t*)"Tanta Parking");
}

void LCD_Display_Empty_Slots(void)
{
    /* Clear display */
    Lcd_SendCommand(&LCD1, 0x01);

    /* First line */
    Lcd_SetCursor(&LCD1, 0, 0);
    Lcd_SendString(&LCD1, (uint8_t*)"Empty Slots=");

    /* Print number at column 13 */
    Lcd_SetCursor(&LCD1, 0, 13);
    Lcd_SendChar(&LCD1, Available_Slots);
}

void LEDs_Init(void)
{
	//RED LED A0

	red_led.PORT=PORTA;
	red_led.PIN_Number=GPIO_PIN0;
	red_led.Active_State=LED_ACTIVE_LOW;
	Led_Init(&red_led);

	//GREEN LED A11

	green_led.PORT=PORTA;
	green_led.PIN_Number=GPIO_PIN11;
	green_led.Active_State=LED_ACTIVE_LOW;
	Led_Init(&green_led);
}

void PIRs_Iint(void)
{
	//PIR1 A7
	GPIO_Config_Pin_t PinCinfg;
	PinCinfg.PORTx=PORTA;
	PinCinfg.Pin_Number=GPIO_PIN7;
	PinCinfg.mode = GPIO_MODE_Input_FLO;
	GPIO_InitPin(&PinCinfg);

	//PIR2 A1
	PinCinfg.PORTx=PORTA;
	PinCinfg.Pin_Number=GPIO_PIN1;
	PinCinfg.mode = GPIO_MODE_Input_FLO;
	GPIO_InitPin(&PinCinfg);

	GPIO_WritePin(PORTA, GPIO_PIN0, 1); //make A0 ground
	GPIO_WritePin(PORTA, GPIO_PIN11, 1); //make A11 ground

}



void Store_IDs_From_Admin(void)
{
    uint8_t i, j, key;

    for(i=0; i<MAX_IDS; i++)
    {
        // Clear LCD before each ID input
        Lcd_SendCommand(&LCD2, 0x01);
        Lcd_SetCursor(&LCD2, 0, 0);
        Lcd_SendString(&LCD2, (uint8_t*)"Enter ID #");
        Lcd_SendChar(&LCD2, '1'+i); // display ID number (1,2,3)
        Lcd_SetCursor(&LCD2, 1, 0);
        Lcd_SendString(&LCD2, (uint8_t*)"ID: ");

        j = 0;
        while(j < ID_LENGTH)
        {
            // Wait until a key is pressed
            if(KeyPad_GetKey(&Keypad3x4, &key) == E_OK)
            {
                if(key >= '0' && key <= '9')
                {
                    // Display key on LCD
                    Lcd_SendChar(&LCD2, key);
                    // Store in array
                    Admin_IDs[i][j] = key;
                    j++;
                    // Debounce using Timer2
                    dms(30); // 30 ms debounce
                }
                else if(key == '#')
                {
                    // Finish this ID early if user presses #
                    break;
                }
                else if(key == '*')
                {
                    // Optional: clear last digit
                    if(j > 0)
                    {
                        j--;
                        // Move cursor back and clear character
                        Lcd_SetCursor(&LCD2, 1, 4 + j);
                        Lcd_SendChar(&LCD2, ' ');
                        Lcd_SetCursor(&LCD2, 1, 4 + j);
                    }
                }
            }
        }
    }

    // After all IDs entered, optional: show confirmation
    Lcd_SendCommand(&LCD2, 0x01);
    Lcd_SetCursor(&LCD2, 0, 0);
    Lcd_SendString(&LCD2, (uint8_t*)"IDs Saved!");
    dms(1000); // 1 second delay
}
void Entring_Fun(void)
{
	if(Available_Slots == '0')
	{
		Lcd_SetCursor(&LCD1,1,0);
		Lcd_SendString(&LCD1,(uint8_t*)"Parking is Full");
		dms(1000);
		return ;
	}

	//Search about ID in array of Pass

	for(uint8_t i = 0; i < MAX_IDS; i++)
	{
	    uint8_t match = 1; // Assume match
	    for(uint8_t j = 0; j < ID_LENGTH; j++)
	    {
	        if(Admin_IDs[i][j] != pass[j])
	        {
	            match = 0; // Not a match
	            break;
	        }
	    }
	    if(match)
	    {
	        Search_Done = 1; // ID found
	        break; // Exit loop
	    }
	}
	// Search_Done = 1; // ID found
	/*=====================Enter gate=====================*/
	if(Search_Done==1)
	{
		Search_Done=0;
		Led_ON(&green_led);
		Servo1_Entry_Gate(UP);
		GPIO_ReadPin(PORTA,GPIO_PIN7,&PIR2);
		while(!PIR2){GPIO_ReadPin(PORTA,GPIO_PIN7,&PIR2);}
		Servo1_Entry_Gate(Down);
		Led_OFF(&green_led);
		Available_Slots--;


	}
	else
	{
		Lcd_SetCursor(&LCD1,0,0);
		Lcd_SendString(&LCD1,(uint8_t*)"Worng ID :( ");
		Lcd_SetCursor(&LCD1,1,0);
		Lcd_SendString(&LCD1,(uint8_t*)"tray again ");
		dms(2000);
		return ;
	}
}

void Exit_Fun(void)
{
	Servo2_Exit_Gate(UP);
	GPIO_ReadPin(PORTA,GPIO_PIN1,&PIR1);
	while(!PIR1){GPIO_ReadPin(PORTA,GPIO_PIN1,&PIR1);}
	Servo2_Exit_Gate(Down);
	Available_Slots++;

}

